const express = require('express');
const multer = require('multer');
const multerS3 = require('multer-s3');
const { DeleteObjectCommand } = require('@aws-sdk/client-s3');
const pool = require('../db/db');        // Postgres Connection
const s3Client = require('../db/minio'); // MinIO Client

const router = express.Router();

// ==========================================
// 1. MinIO Configuration
// ==========================================
const BUCKET_NAME = 'authorities'; // Bucket updated as requested

const upload = multer({
  storage: multerS3({
    s3: s3Client,
    bucket: BUCKET_NAME,
    contentType: multerS3.AUTO_CONTENT_TYPE,
    metadata: function (req, file, cb) {
      cb(null, { fieldName: file.fieldname });
    },
    key: function (req, file, cb) {
      // Create a unique file name to avoid overwrites
      // Example: 167890123-meeting-minutes.pdf
      const uniqueName = `${Date.now()}-${file.originalname.replace(/\s+/g, '-')}`;
      cb(null, uniqueName);
    }
  })
});

// Middleware for single file upload (field name: 'file')
const uploadFile = upload.single('file');

// ==========================================
// 2. Helper Functions
// ==========================================

// Deletes a file from MinIO given its full URL
const deleteMinioFile = async (fileUrl) => {
  if (!fileUrl) return;
  
  try {
    // Extract the key (filename) from the full URL
    // Example URL: http://localhost:9000/authorities/123-file.pdf -> Key: 123-file.pdf
    const fileKey = decodeURIComponent(fileUrl.split('/').pop());

    await s3Client.send(new DeleteObjectCommand({
      Bucket: BUCKET_NAME,
      Key: fileKey,
    }));
    
    console.log(`[MinIO] Deleted file: ${fileKey}`);
  } catch (err) {
    console.error(`[MinIO] Error deleting file (${fileUrl}):`, err);
  }
};

// ==========================================
// 3. API Routes for 'authorities' table
// ==========================================

// GET: Fetch all authorities
router.get('/', async (req, res) => {
  try {
    const query = 'SELECT * FROM authorities ORDER BY id ASC';
    const result = await pool.query(query);
    res.json(result.rows);
  } catch (err) {
    console.error('GET /authorities error:', err);
    res.status(500).json({ error: err.message });
  }
});

// POST: Create new authority record with file upload
router.post('/', uploadFile, async (req, res) => {
  try {
    const { title, name } = req.body;
    
    // req.file.location contains the MinIO URL generated by multer-s3
    const titleHref = req.file ? req.file.location : null;

    if (!titleHref) {
      return res.status(400).json({ error: 'File upload is required.' });
    }

    const query = `
      INSERT INTO authorities (title, name, title_href)
      VALUES ($1, $2, $3)
      RETURNING *
    `;
    
    const result = await pool.query(query, [title, name, titleHref]);
    
    res.status(201).json(result.rows[0]);
  } catch (err) {
    console.error('POST /authorities error:', err);
    res.status(500).json({ error: err.message });
  }
});

// PUT: Update authority record (replace file if new one provided)
router.put('/:id', uploadFile, async (req, res) => {
  try {
    const { id } = req.params;
    const { title, name } = req.body;

    // 1. Fetch the existing record to get the old file URL
    const oldRecord = await pool.query('SELECT * FROM authorities WHERE id = $1', [id]);
    
    if (oldRecord.rows.length === 0) {
      return res.status(404).json({ error: 'Record not found' });
    }

    let currentHref = oldRecord.rows[0].title_href;

    // 2. If a new file is uploaded...
    if (req.file) {
      // Delete the old file from MinIO
      await deleteMinioFile(currentHref);
      // Set the new URL
      currentHref = req.file.location;
    }

    // 3. Update the database
    const query = `
      UPDATE authorities 
      SET title = $1, name = $2, title_href = $3
      WHERE id = $4
      RETURNING *
    `;

    const result = await pool.query(query, [title, name, currentHref, id]);
    
    res.json(result.rows[0]);
  } catch (err) {
    console.error('PUT /authorities/:id error:', err);
    res.status(500).json({ error: err.message });
  }
});

// DELETE: Remove authority record and associated file
router.delete('/:id', async (req, res) => {
  try {
    const { id } = req.params;

    // 1. Fetch the record to find the file URL
    const result = await pool.query('SELECT title_href FROM authorities WHERE id = $1', [id]);

    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Record not found' });
    }

    const fileUrl = result.rows[0].title_href;

    // 2. Delete the file from MinIO
    if (fileUrl) {
      await deleteMinioFile(fileUrl);
    }

    // 3. Delete the record from the database
    await pool.query('DELETE FROM authorities WHERE id = $1', [id]);

    res.json({ success: true, message: 'Authority deleted successfully' });
  } catch (err) {
    console.error('DELETE /authorities/:id error:', err);
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;